package model;
// Generated Apr 13, 2018 2:33:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Angsuran generated by hbm2java
 */
public class Angsuran  implements java.io.Serializable {


     private String idAngsuran;
     private Customer customer;
     private Gadai gadai;
     private Date tanggalAngsuran;
     private Long jumlahAngsuran;
     private Long denda;

    public Angsuran() {
    }

	
    public Angsuran(String idAngsuran, Customer customer, Gadai gadai) {
        this.idAngsuran = idAngsuran;
        this.customer = customer;
        this.gadai = gadai;
    }
    public Angsuran(String idAngsuran, Customer customer, Gadai gadai, Date tanggalAngsuran, Long jumlahAngsuran, Long denda) {
       this.idAngsuran = idAngsuran;
       this.customer = customer;
       this.gadai = gadai;
       this.tanggalAngsuran = tanggalAngsuran;
       this.jumlahAngsuran = jumlahAngsuran;
       this.denda = denda;
    }
   
    public String getIdAngsuran() {
        return this.idAngsuran;
    }
    
    public void setIdAngsuran(String idAngsuran) {
        this.idAngsuran = idAngsuran;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Gadai getGadai() {
        return this.gadai;
    }
    
    public void setGadai(Gadai gadai) {
        this.gadai = gadai;
    }
    public Date getTanggalAngsuran() {
        return this.tanggalAngsuran;
    }
    
    public void setTanggalAngsuran(Date tanggalAngsuran) {
        this.tanggalAngsuran = tanggalAngsuran;
    }
    public Long getJumlahAngsuran() {
        return this.jumlahAngsuran;
    }
    
    public void setJumlahAngsuran(Long jumlahAngsuran) {
        this.jumlahAngsuran = jumlahAngsuran;
    }
    public Long getDenda() {
        return this.denda;
    }
    
    public void setDenda(Long denda) {
        this.denda = denda;
    }




}


