package model;
// Generated Apr 13, 2018 2:33:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String idCustomer;
     private Long nomorKtp;
     private String namaCustomer;
     private String nomorTelepon;
     private String pekerjaan;
     private String alamat;
     private Set<Gadai> gadais = new HashSet<Gadai>(0);
     private Set<Angsuran> angsurans = new HashSet<Angsuran>(0);

    public Customer() {
    }

	
    public Customer(String idCustomer) {
        this.idCustomer = idCustomer;
    }
    public Customer(String idCustomer, Long nomorKtp, String namaCustomer, String nomorTelepon, String pekerjaan, String alamat, Set<Gadai> gadais, Set<Angsuran> angsurans) {
       this.idCustomer = idCustomer;
       this.nomorKtp = nomorKtp;
       this.namaCustomer = namaCustomer;
       this.nomorTelepon = nomorTelepon;
       this.pekerjaan = pekerjaan;
       this.alamat = alamat;
       this.gadais = gadais;
       this.angsurans = angsurans;
    }
   
    public String getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(String idCustomer) {
        this.idCustomer = idCustomer;
    }
    public Long getNomorKtp() {
        return this.nomorKtp;
    }
    
    public void setNomorKtp(Long nomorKtp) {
        this.nomorKtp = nomorKtp;
    }
    public String getNamaCustomer() {
        return this.namaCustomer;
    }
    
    public void setNamaCustomer(String namaCustomer) {
        this.namaCustomer = namaCustomer;
    }
    public String getNomorTelepon() {
        return this.nomorTelepon;
    }
    
    public void setNomorTelepon(String nomorTelepon) {
        this.nomorTelepon = nomorTelepon;
    }
    public String getPekerjaan() {
        return this.pekerjaan;
    }
    
    public void setPekerjaan(String pekerjaan) {
        this.pekerjaan = pekerjaan;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set<Gadai> getGadais() {
        return this.gadais;
    }
    
    public void setGadais(Set<Gadai> gadais) {
        this.gadais = gadais;
    }
    public Set<Angsuran> getAngsurans() {
        return this.angsurans;
    }
    
    public void setAngsurans(Set<Angsuran> angsurans) {
        this.angsurans = angsurans;
    }




}


