package model;
// Generated Apr 13, 2018 2:33:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gadai generated by hbm2java
 */
public class Gadai  implements java.io.Serializable {


     private String idGadai;
     private Barang barang;
     private Customer customer;
     private Long jumlahPinjaman;
     private Date tanggalPinjaman;
     private Date jatuhTempo;
     private Long sisa;
     private Set<Angsuran> angsurans = new HashSet<Angsuran>(0);

    public Gadai() {
    }

	
    public Gadai(String idGadai, Barang barang, Customer customer) {
        this.idGadai = idGadai;
        this.barang = barang;
        this.customer = customer;
    }
    public Gadai(String idGadai, Barang barang, Customer customer, Long jumlahPinjaman, Date tanggalPinjaman, Date jatuhTempo, Long sisa, Set<Angsuran> angsurans) {
       this.idGadai = idGadai;
       this.barang = barang;
       this.customer = customer;
       this.jumlahPinjaman = jumlahPinjaman;
       this.tanggalPinjaman = tanggalPinjaman;
       this.jatuhTempo = jatuhTempo;
       this.sisa = sisa;
       this.angsurans = angsurans;
    }
   
    public String getIdGadai() {
        return this.idGadai;
    }
    
    public void setIdGadai(String idGadai) {
        this.idGadai = idGadai;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Long getJumlahPinjaman() {
        return this.jumlahPinjaman;
    }
    
    public void setJumlahPinjaman(Long jumlahPinjaman) {
        this.jumlahPinjaman = jumlahPinjaman;
    }
    public Date getTanggalPinjaman() {
        return this.tanggalPinjaman;
    }
    
    public void setTanggalPinjaman(Date tanggalPinjaman) {
        this.tanggalPinjaman = tanggalPinjaman;
    }
    public Date getJatuhTempo() {
        return this.jatuhTempo;
    }
    
    public void setJatuhTempo(Date jatuhTempo) {
        this.jatuhTempo = jatuhTempo;
    }
    public Long getSisa() {
        return this.sisa;
    }
    
    public void setSisa(Long sisa) {
        this.sisa = sisa;
    }
    public Set<Angsuran> getAngsurans() {
        return this.angsurans;
    }
    
    public void setAngsurans(Set<Angsuran> angsurans) {
        this.angsurans = angsurans;
    }




}


