package model;
// Generated Apr 13, 2018 2:33:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JenisBarang generated by hbm2java
 */
public class JenisBarang  implements java.io.Serializable {


     private String idJenisBarang;
     private String namaJenisBarang;
     private Set<Barang> barangs = new HashSet<Barang>(0);

    public JenisBarang() {
    }

	
    public JenisBarang(String idJenisBarang) {
        this.idJenisBarang = idJenisBarang;
    }
    public JenisBarang(String idJenisBarang, String namaJenisBarang, Set<Barang> barangs) {
       this.idJenisBarang = idJenisBarang;
       this.namaJenisBarang = namaJenisBarang;
       this.barangs = barangs;
    }
   
    public String getIdJenisBarang() {
        return this.idJenisBarang;
    }
    
    public void setIdJenisBarang(String idJenisBarang) {
        this.idJenisBarang = idJenisBarang;
    }
    public String getNamaJenisBarang() {
        return this.namaJenisBarang;
    }
    
    public void setNamaJenisBarang(String namaJenisBarang) {
        this.namaJenisBarang = namaJenisBarang;
    }
    public Set<Barang> getBarangs() {
        return this.barangs;
    }
    
    public void setBarangs(Set<Barang> barangs) {
        this.barangs = barangs;
    }




}


